# -*- coding: utf-8 -*-
BOAT_CLASS_IN = "in"
BOAT_CLASS_OUT = "out"
BOAT_CLASS_BOAT = "boat"

BOAT_TYPE_MOTOR = "motor"
BOAT_TYPE_SEAL = "seal"

PHOTO_TYPES = [BOAT_CLASS_BOAT, BOAT_CLASS_OUT]
BOAT_TYPES = [BOAT_TYPE_MOTOR, BOAT_TYPE_SEAL]
PHOTO_TYPES_ALL = [BOAT_CLASS_BOAT, BOAT_CLASS_IN, BOAT_CLASS_OUT]

BOAT_TYPE = "boat_type"
PHOTO_TYPE = "photo_type"
BOAT_MODEL = "boat_model"
IMAGE_PATH = "image_path"

MAX_EPOCHS = 25
BATCH_SIZE = 16
TRANSFORM_SIZE = (224, 224)

DEFAULT_CSV_PATH = "./data/boat_pictures_dataset.csv"
HEATMAP_FOLDER = "./heatmap"
TOP = 5
THRESHOLD = 90
MODEL_THRESHOLD = 65

HOST = "0.0.0.0"
PORT = 8000
